### ISSUE TITLE
Marriage needs an update /Marry displays this error on 1.12

### ISSUE THREAD

**Issue by Fonzee9** [lenis0012/Marriage#29]
https://pastebin.com/1x39ndP4

**Comment by lenis0012** [comment]
I will look into this later this week.
Though i will not officially support any pre-release builds, I will only fix it if this issue will likely occur in the official build as well

**Comment by Fonzee9** [comment]
Why not support pre release builds? Once you update it it will work on the official release of 1.12. Griefprevention , dicefurniture, fastayncworldedit have already been updated to 1.12 pre 2

**Comment by lenis0012** [comment]
@Fonzee9 I will not officially support unofficial builds.
It's that simple.

But like I said, if the issue is likely to occur on the official 1.12 build as well, I will fix it and you will be able to download a compatible build on http://ci.lenis0012.com/

I will keep you up to date.

**Comment by jordanwilliams1** [comment]
@lenis0012 Players love this plugin on our server, Can we get an update out?

**Comment by Alex-231** [comment]
The commands and command aliases map isn't populated, commands aren't being registered correctly. As far as I can tell, the findclasses method is not returning anything, and this might be due to the guava update. I can't say for sure tho, I didn't do much debugging and I'm not too experienced with minecraft plugins.

That said, I have created a hacky patch for this plugin on [my fork.](https://github.com/AlexAndLuke/Marriage). I used this on my server for a little while, and it seems to work fine. Thought I'd leave this here for anyone who really needs an update.

**Comment by games647** [comment]
@Alex-231 Could you make a pull request then?

**Comment by lenis0012** [comment]
@games647 I will resolve the issue tonight.

**Comment by lenis0012** [comment]
@games647 Well it's been a few weeks but it should be resolved

**Comment by lenis0012** [comment]
Closing this old issue. Moving forward for 1.14 support
